/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jinlin_encryptutils_base64_Base64 */

#ifndef _Included_com_jinlin_encryptutils_base64_Base64
#define _Included_com_jinlin_encryptutils_base64_Base64
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jinlin_encryptutils_base64_Base64
 * Method:    encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jinlin_encryptutils_base64_Base64_encode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jinlin_encryptutils_base64_Base64
 * Method:    decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jinlin_encryptutils_base64_Base64_decode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
