/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jinlin_encryptutils_des_DES */

#ifndef _Included_com_jinlin_encryptutils_des_DES
#define _Included_com_jinlin_encryptutils_des_DES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jinlin_encryptutils_des_DES
 * Method:    desCrypt
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jinlin_encryptutils_des_DES_desCrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
