/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jinlin_encryptutils_aes_AES */

#ifndef _Included_com_jinlin_encryptutils_aes_AES
#define _Included_com_jinlin_encryptutils_aes_AES
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jinlin_encryptutils_aes_AES_ENCRYPT
#define com_jinlin_encryptutils_aes_AES_ENCRYPT 0L
#undef com_jinlin_encryptutils_aes_AES_DECRYPT
#define com_jinlin_encryptutils_aes_AES_DECRYPT 1L
/*
 * Class:     com_jinlin_encryptutils_aes_AES
 * Method:    crypt
 * Signature: ([BJI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jinlin_encryptutils_aes_AES_crypt
  (JNIEnv *, jclass, jbyteArray, jlong, jint);

/*
 * Class:     com_jinlin_encryptutils_aes_AES
 * Method:    read
 * Signature: (Ljava/lang/String;J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jinlin_encryptutils_aes_AES_read
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
