/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jinlin_encryptutils_md5_MD5 */

#ifndef _Included_com_jinlin_encryptutils_md5_MD5
#define _Included_com_jinlin_encryptutils_md5_MD5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jinlin_encryptutils_md5_MD5
 * Method:    encryptByMD5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jinlin_encryptutils_md5_MD5_encryptByMD5
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
